### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by seconds7** [amdegroot/ssd.pytorch#37] opened 2017-07-16 06:43 UTC
when I run 'python -m demo.live', it occurs to me.  The environment is conda and python3.5, how can I solve it?

**Comment by amdegroot** [comment] 2017-08-03 11:01
Sorry I don't understand, can you please clarify what the issue is here?  I can't reproduce this so I'm closing for now.

**Closed by amdegroot** 2017-08-03 11:01 UTC
